format = """
$os\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$all\
$character\
"""

#$all\
add_newline = false

palette = 'korompalette'

[palettes.korompalette]
red = '#e63946'
orange = '#efb627'

[fill]
symbol = ' '

[os]
disabled = false
style = 'bold cyan'
format = '[$symbol ]($style)'

[os.symbols]
Macos = "󰀵"
Windows = "󰍲"
Ubuntu = "󰕈"

[status]
disabled = false
symbol = '[✗](bold red) '

[cmd_duration]
show_milliseconds = true
format = "[   $duration ]($style)"
show_notifications = true
min_time_to_notify = 30_000

[git_branch]
symbol = " "
style = 'bold orange'
format = '[$symbol$branch(:$remote_branch)]($style) '

# Adds personalised characters for each status. 
# Adds a space after each status.
# Adds optional backspaces to the start and end of the enclosing braces, to counteract the spaces.
[git_status]
format = "[$all_status$ahead_behind\b]($style) "
conflicted = '*${count} '
ahead = '[⇡${count}](fg:green)'
behind = '[⇣${count}](fg:blue)'
diverged= '⇕\(⇡${ahead_count} ⇣${behind_count}\) '
untracked = '+${count} '
stashed = '\[${count}\] '
modified = '~${count} '
staged = '[+${count}](fg:green) '
renamed = '[»${count}](fg:cyan) '
deleted	= '-${count} '

[git_commit]
tag_disabled = false

[nodejs]
format = ' [$symbol($version )]($style)'

[php]
format = ' [$symbol($version )]($style)'
symbol = " "

[golang]
format = ' [$symbol($version )]($style)'
symbol = " "

[rust]
format = ' [$symbol($version )]($style)'
symbol = " "
